# Generated by Django 5.2 on 2025-07-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionairesManager", "0003_section_question_section"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="section",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="section",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("questionnaire", "name")},
        ),
    ]
