# Generated by Django 5.2 on 2025-07-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionairesManager", "0005_alter_choice_id_alter_question_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
