# Generated by Django 5.2 on 2025-07-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionairesManager", "0006_alter_choice_id_alter_question_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
