# Generated by Django 5.2 on 2025-07-12 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabSurveyResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LabResultEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=100)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("numeric", "Wartość liczbowa"),
                            ("text", "Opis tekstowy"),
                            ("choice", "Wybór: pozytywny/negatywny"),
                        ],
                        default="numeric",
                        max_length=10,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("reference_min", models.FloatField(blank=True, null=True)),
                ("reference_max", models.FloatField(blank=True, null=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="labTest.labsurveyresult",
                    ),
                ),
            ],
        ),
    ]
