# Generated by Django 5.2 on 2025-07-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labTest", "0002_labsurveyresult_date_labsurveyresult_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labresultentry",
            name="value",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
