# Generated by Django 5.2 on 2025-07-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labTest", "0003_alter_labresultentry_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labresultentry",
            name="reference_max",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="labresultentry",
            name="reference_min",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
    ]
