# Generated by Django 5.2 on 2025-07-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labTest", "0004_alter_labresultentry_reference_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="labresultentry",
            name="section",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
