# Generated by Django 5.2 on 2025-07-22 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionairesManager", "0006_alter_choice_id_alter_question_id_and_more"),
        ("questionairesPatient", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentquestionnairerequest",
            name="questionnaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_requests_from_patient",
                to="questionairesManager.questionnaire",
            ),
        ),
    ]
