# Generated by Django 5.2 on 2025-07-09 18:29

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authCustom", "0002_patientprofile_specialistprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="license_number",
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Numer telefonu musi zawierać od 9 do 15 cyfr i może zaczynać się od '+'",
                        regex="^(\\+?\\d{9,15})$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="second_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="insurance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NFZ", "NFZ"),
                    ("PRIVATE", "Ubezpieczenie prywatne"),
                    ("NONE", "Brak ubezpieczenia"),
                ],
                default="NFZ",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="specialistprofile",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="specialistprofile",
            name="description",
            field=models.TextField(blank=True, verbose_name="Opis o mnie"),
        ),
        migrations.AddField(
            model_name="specialistprofile",
            name="education",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="specialistprofile",
            name="experience",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="specialistprofile",
            name="license_number",
            field=models.CharField(
                blank=True,
                max_length=7,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Numer PWZ powinien zawierać 6–7 cyfr.",
                        regex="^\\d{6,7}$",
                    )
                ],
                verbose_name="Numer PWZ",
            ),
        ),
        migrations.AddField(
            model_name="specialistprofile",
            name="location",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Adres przyjęć"
            ),
        ),
        migrations.AddField(
            model_name="specialistprofile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.AddField(
            model_name="specialistprofile",
            name="second_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="specialistprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="pesel",
            field=models.CharField(
                blank=True,
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="PESEL musi zawierać dokładnie 11 cyfr.",
                        regex="^\\d{11}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="specialistprofile",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Numer telefonu musi zawierać od 9 do 15 cyfr i może zaczynać się od '+'",
                        regex="^(\\+?\\d{9,15})$",
                    )
                ],
            ),
        ),
    ]
