# Generated by Django 5.2 on 2025-07-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="content",
            field=models.TextField(default="Brak treści"),
        ),
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.CharField(default="(bez tematu)", max_length=255),
        ),
    ]
