# Generated by Django 5.2 on 2025-07-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mySpecialist", "0004_sentquestionnairerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
