"""
Django settings for webApp project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'your-default-secret-key-for-local-development')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# RAG_BASE_DIR = BASE_DIR / "predictionModels/services/models/rag"
# RAG_TXT_DIR  = "definitions_of_specjalists"
# RAG_PDF_DIR  = "books"
RAG_BASE_DIR = BASE_DIR / "predictionModels" / "services" / "models" / "rag"
RAG_TXT_DIR   = RAG_BASE_DIR / "definitions_of_specjalists"
RAG_PDF_DIR   = RAG_BASE_DIR / "books"
RAG_NOTES_FILE = RAG_BASE_DIR / "notes" / "notatki.txt"

# katalog z wagami Mistrala (lokalny, gdzie masz tokenizer.json, config.json, pytorch_model-*.bin itd.)
MISTRAL_MODEL_DIR = BASE_DIR / "predictionModels" / "services" / "models" / "mistral" / "mistral_model"

# (RAG) katalog z wektorami / FAISS (dostosuj do siebie)
MISTRAL_RAG_INDEX_DIR = BASE_DIR / "predictionModels" / "services" / "models" / "mistral" / "rag_index"

ALLOWED_HOSTS = ['*']

load_dotenv()

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',

    'django_bootstrap5',

    'authCustom',
    'cald',
    'wellnessTracker',
    'Statistics',
    'homePatient',
    'homeSpecialist',
    'questionairesManager',
    'labTest',
    'mySpecialist',
    'questionairesPatient',
    'messaging',
    # 'predictionModels',
    "predictionModels.apps.PredictionModelsConfig",

]
LOGIN_REDIRECT_URL = '/redirect-by-role/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webApp.wsgi.application'

# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_URL = os.environ.get("DJANGO_STATIC_URL", "/static/")
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

if DEBUG:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"

# myproject/settings.py

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = 'login'
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30

SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

AUTH_USER_MODEL = 'authCustom.CustomUser'
